//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23102_Formova_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criteria
    {
        public Criteria()
        {
            this.StudentResult = new HashSet<StudentResult>();
        }
    
        public int IdCriteria { get; set; }
        public int IdDiscipline { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string NumberOfPionts { get; set; }
        public string WithdrawPercent { get; set; }
        public string RemoveAPoint { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual ICollection<StudentResult> StudentResult { get; set; }
    }
}
