//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23102_Formova_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        public Discipline()
        {
            this.Attestation = new HashSet<Attestation>();
            this.Criteria = new HashSet<Criteria>();
            this.DisciplineTeachers = new HashSet<DisciplineTeachers>();
        }
    
        public int IdDiscipline { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Attestation> Attestation { get; set; }
        public virtual ICollection<Criteria> Criteria { get; set; }
        public virtual ICollection<DisciplineTeachers> DisciplineTeachers { get; set; }
    }
}
