//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23102_Formova_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplineTeachers
    {
        public int IdDiscipline { get; set; }
        public int IdTeacher { get; set; }
        public int IdDisciplineTeachers { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
