//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23102_Formova_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speciality
    {
        public Speciality()
        {
            this.Group = new HashSet<Group>();
            this.Teachers = new HashSet<Teachers>();
        }
    
        public int IdSpeciality { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Group> Group { get; set; }
        public virtual ICollection<Teachers> Teachers { get; set; }
    }
}
