//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23102_Formova_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentResult = new HashSet<StudentResult>();
            this.Vedomosti = new HashSet<Vedomosti>();
        }
    
        public int IdStudent { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public int IdGroup { get; set; }
        public int IdSpeciality { get; set; }
        public int IdStatusStudent { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual StatusStudent StatusStudent { get; set; }
        public virtual ICollection<StudentResult> StudentResult { get; set; }
        public virtual ICollection<Vedomosti> Vedomosti { get; set; }
    }
}
