//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23102_Formova_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public int IdSystemUsers { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
    
        public virtual Teachers Teachers { get; set; }
    }
}
